name: "CodeQL Devin Fixer"
description: "Run CodeQL analysis, prioritize security issues, and dispatch Devin sessions to fix them in batches"

inputs:
  target_repo:
    description: "GitHub repository to analyze. Accepts full URL (https://github.com/owner/repo) or owner/repo shorthand."
    required: true
  github_token:
    description: "GitHub token for fork operations, log persistence, and dashboard generation. MUST be a Personal Access Token (PAT) with 'repo' scope for fork creation and push. The default GITHUB_TOKEN cannot fork or push to other repos."
    required: false
    default: ""
  languages:
    description: "Comma-separated CodeQL languages (e.g., javascript,python). Auto-detected if empty."
    required: false
    default: ""
  queries:
    description: "CodeQL query suite to run (e.g., security-extended, security-and-quality)"
    required: false
    default: "security-extended"
  include_paths:
    description: "Optional newline- or comma-separated globs to include (limits analysis scope)"
    required: false
    default: ""
  exclude_paths:
    description: "Optional newline- or comma-separated globs to exclude from analysis"
    required: false
    default: ""
  batch_size:
    description: "Maximum number of issues per Devin session/batch"
    required: false
    default: "5"
  max_sessions:
    description: "Maximum number of Devin sessions to create"
    required: false
    default: "25"
  severity_threshold:
    description: "Minimum severity to include: critical, high, medium, low"
    required: false
    default: "low"
  devin_api_key:
    description: "Devin API key for creating fix sessions"
    required: true
  max_acu_per_session:
    description: "Maximum ACU limit per Devin session (leave empty for default)"
    required: false
    default: ""
  dry_run:
    description: "If true, generate prompts but don't create Devin sessions"
    required: false
    default: "false"
  default_branch:
    description: "Default branch of the target repo"
    required: false
    default: "main"
  persist_logs:
    description: "Persist run logs to the fork repository"
    required: false
    default: "true"

outputs:
  total_issues:
    description: "Total number of security issues found"
    value: ${{ steps.parse.outputs.total_issues }}
  total_batches:
    description: "Number of batches created"
    value: ${{ steps.parse.outputs.total_batches }}
  sessions_created:
    description: "Number of Devin sessions created"
    value: ${{ steps.dispatch.outputs.sessions_created }}
  sessions_failed:
    description: "Number of Devin sessions that failed to create"
    value: ${{ steps.dispatch.outputs.sessions_failed }}
  session_urls:
    description: "Comma-separated list of Devin session URLs"
    value: ${{ steps.dispatch.outputs.session_urls }}
  fork_url:
    description: "URL of the fork used for scanning"
    value: ${{ steps.fork.outputs.fork_url }}
  run_label:
    description: "Label for this run's logs"
    value: ${{ steps.parse.outputs.run_label }}
  logs_persisted:
    description: "Whether run logs were successfully pushed to the fork"
    value: ${{ steps.persist-logs.outputs.logs_persisted }}

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      timeout-minutes: 5
      with:
        python-version: "3.11"

    - name: Install Python dependencies
      shell: bash
      timeout-minutes: 3
      run: pip install requests jinja2

    - name: Normalize target repo URL
      id: normalize
      shell: bash
      timeout-minutes: 1
      run: |
        RAW="${{ inputs.target_repo }}"
        RAW=$(echo "$RAW" | sed 's|^[[:space:]]*||;s|[[:space:]]*$||;s|/$||')
        RAW=$(echo "$RAW" | sed 's|\.git$||')
        if ! echo "$RAW" | grep -qE '^https?://'; then
          if echo "$RAW" | grep -qE '^[A-Za-z0-9._-]+/[A-Za-z0-9._-]+$'; then
            RAW="https://github.com/$RAW"
          fi
        fi
        echo "target_repo=$RAW" >> "$GITHUB_OUTPUT"
        echo "Normalized target_repo: $RAW"

    - name: Fork or verify target repository
      id: fork
      shell: bash
      timeout-minutes: 5
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        TARGET_REPO: ${{ steps.normalize.outputs.target_repo }}
        DEFAULT_BRANCH: ${{ inputs.default_branch }}
        FORK_OWNER: ${{ github.repository_owner }}
      run: |
        if [ -n "$GITHUB_TOKEN" ]; then
          python "${{ github.action_path }}/scripts/fork_repo.py"
        else
          echo "fork_url=${{ steps.normalize.outputs.target_repo }}" >> "$GITHUB_OUTPUT"
          echo "No GITHUB_TOKEN provided; using original repo URL"
        fi

    - name: Clone target repository
      shell: bash
      timeout-minutes: 10
      env:
        GIT_LFS_SKIP_SMUDGE: "1"
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        TARGET_DIR="${{ runner.temp }}/target-repo"
        REPO_URL="${{ steps.fork.outputs.fork_url }}"
        if [ -z "$REPO_URL" ]; then
          REPO_URL="${{ steps.normalize.outputs.target_repo }}"
        fi
        CLONE_URL="$REPO_URL"
        if [ -n "$GITHUB_TOKEN" ]; then
          CLONE_URL=$(echo "$REPO_URL" | sed "s|https://github.com/|https://x-access-token:${GITHUB_TOKEN}@github.com/|")
        fi
        git clone --depth 1 --single-branch "$CLONE_URL" "$TARGET_DIR"
        echo "TARGET_DIR=$TARGET_DIR" >> "$GITHUB_ENV"
        echo "SCAN_REPO_URL=$REPO_URL" >> "$GITHUB_ENV"

    - name: Detect languages
      id: detect-lang
      shell: bash
      timeout-minutes: 3
      run: |
        if [ -n "${{ inputs.languages }}" ]; then
          echo "languages=${{ inputs.languages }}" >> "$GITHUB_OUTPUT"
          echo "Using specified languages: ${{ inputs.languages }}"
          exit 0
        fi

        TARGET_DIR="${{ runner.temp }}/target-repo"
        LANGS=""

        has_files() {
          local result
          result=$(find "$TARGET_DIR" \( "$@" \) -print -quit 2>/dev/null)
          [ -n "$result" ]
        }

        has_manifest() {
          local f
          for f in "$@"; do
            if [ -f "$TARGET_DIR/$f" ]; then
              return 0
            fi
          done
          return 1
        }

        PHP_PRESENT=0
        if has_manifest composer.json || has_files -name "*.php"; then
          PHP_PRESENT=1
        fi

        if has_manifest package.json tsconfig.json || has_files -name "*.js" -o -name "*.ts" -o -name "*.jsx" -o -name "*.tsx"; then
          LANGS="${LANGS:+$LANGS,}javascript"
        fi
        if has_manifest setup.py setup.cfg pyproject.toml Pipfile || has_files -name "*.py"; then
          LANGS="${LANGS:+$LANGS,}python"
        fi
        if has_manifest pom.xml build.gradle build.gradle.kts || has_files -name "*.java"; then
          LANGS="${LANGS:+$LANGS,}java"
        fi
        if has_manifest go.mod || has_files -name "*.go"; then
          LANGS="${LANGS:+$LANGS,}go"
        fi
        if has_manifest Gemfile || has_files -name "*.rb"; then
          LANGS="${LANGS:+$LANGS,}ruby"
        fi
        if has_files -name "*.cs" -o -name "*.csproj" -o -name "*.sln"; then
          LANGS="${LANGS:+$LANGS,}csharp"
        fi
        if has_manifest CMakeLists.txt Makefile || has_files -name "*.cpp" -o -name "*.c" -o -name "*.h"; then
          LANGS="${LANGS:+$LANGS,}cpp"
        fi
        if has_manifest Package.swift || has_files -name "*.swift"; then
          LANGS="${LANGS:+$LANGS,}swift"
        fi

        if [ -z "$LANGS" ]; then
          if [ "$PHP_PRESENT" -eq 1 ]; then
            echo "ERROR: Detected PHP-only repository. CodeQL does not support PHP. Supported languages: cpp,csharp,go,java,javascript,python,ruby,swift" >&2
            if [ -n "$GITHUB_STEP_SUMMARY" ]; then
              printf "\n**ERROR**: Detected PHP-only repository. CodeQL does not support PHP.\n\nSupported languages: cpp, csharp, go, java, javascript, python, ruby, swift\n" >> "$GITHUB_STEP_SUMMARY"
            fi
            exit 1
          fi
          echo "No supported languages detected, defaulting to javascript"
          LANGS="javascript"
        fi

        if [ "$PHP_PRESENT" -eq 1 ]; then
          echo "WARNING: PHP detected. CodeQL does not support PHP; results will exclude PHP issues."
          if [ -n "$GITHUB_STEP_SUMMARY" ]; then
            printf "\n**Note**: PHP detected. CodeQL does not support PHP; results will exclude PHP issues.\n" >> "$GITHUB_STEP_SUMMARY"
          fi
        fi

        echo "languages=$LANGS" >> "$GITHUB_OUTPUT"
        echo "Detected languages: $LANGS"

    - name: Prepare CodeQL config
      id: prepare-config
      shell: bash
      timeout-minutes: 1
      run: |
        CONFIG="${{ runner.temp }}/codeql-config.yml"
        INC="${{ inputs.include_paths }}"
        EXC="${{ inputs.exclude_paths }}"
        sanitize() {
          echo "$1" | tr ',' '\n' | sed '/^\s*$/d' | sed 's/^\s*//;s/\s*$//'
        }
        has_config=false
        echo "version: 2" > "$CONFIG"
        echo "queries: ${{ inputs.queries }}" >> "$CONFIG"
        INCL=$(sanitize "$INC")
        EXCL=$(sanitize "$EXC")
        if [ -n "$INCL" ] || [ -n "$EXCL" ]; then
          has_config=true
          echo "paths:" >> "$CONFIG"
          if [ -n "$INCL" ]; then
            sanitize "$INC" | sed 's/^/- /' >> "$CONFIG"
          fi
          if [ -n "$EXCL" ]; then
            echo "paths-ignore:" >> "$CONFIG"
            sanitize "$EXC" | sed 's/^/- /' >> "$CONFIG"
          fi
        fi
        echo "config_path=$CONFIG" >> "$GITHUB_OUTPUT"
        echo "has_config=$has_config" >> "$GITHUB_OUTPUT"

    - name: Initialize CodeQL (with config)
      if: steps.prepare-config.outputs.has_config == 'true'
      uses: github/codeql-action/init@v3
      timeout-minutes: 10
      with:
        languages: ${{ steps.detect-lang.outputs.languages }}
        source-root: ${{ runner.temp }}/target-repo
        config-file: ${{ steps.prepare-config.outputs.config_path }}

    - name: Initialize CodeQL
      if: steps.prepare-config.outputs.has_config != 'true'
      uses: github/codeql-action/init@v3
      timeout-minutes: 10
      with:
        languages: ${{ steps.detect-lang.outputs.languages }}
        source-root: ${{ runner.temp }}/target-repo
        queries: ${{ inputs.queries }}

    - name: Build CodeQL database (autobuild)
      uses: github/codeql-action/autobuild@v3
      timeout-minutes: 30
      env:
        LGTM_SRC: ${{ runner.temp }}/target-repo

    - name: Run CodeQL analysis
      uses: github/codeql-action/analyze@v3
      id: codeql-analyze
      timeout-minutes: 30
      with:
        output: ${{ runner.temp }}/codeql-results
        upload: never
        upload-database: true
        wait-for-processing: true

    - name: Find SARIF file
      id: find-sarif
      shell: bash
      timeout-minutes: 1
      run: |
        SARIF_DIR="${{ runner.temp }}/codeql-results"
        SARIF_FILE=$(find "$SARIF_DIR" -name "*.sarif" -type f | head -1)
        if [ -z "$SARIF_FILE" ]; then
          echo "ERROR: No SARIF file found in $SARIF_DIR"
          ls -la "$SARIF_DIR" || true
          exit 1
        fi
        echo "sarif_file=$SARIF_FILE" >> "$GITHUB_OUTPUT"
        echo "Found SARIF: $SARIF_FILE"

    - name: Parse SARIF and create batches
      id: parse
      shell: bash
      timeout-minutes: 10
      env:
        BATCH_SIZE: ${{ inputs.batch_size }}
        MAX_SESSIONS: ${{ inputs.max_sessions }}
        SEVERITY_THRESHOLD: ${{ inputs.severity_threshold }}
        RUN_NUMBER: ${{ github.run_number }}
      run: |
        python "${{ github.action_path }}/scripts/parse_sarif.py" \
          "${{ runner.temp }}/codeql-results" \
          "${{ runner.temp }}/codeql-output"

    - name: Dispatch Devin sessions
      id: dispatch
      shell: bash
      timeout-minutes: 15
      env:
        DEVIN_API_KEY: ${{ inputs.devin_api_key }}
        TARGET_REPO: ${{ env.SCAN_REPO_URL }}
        FORK_URL: ${{ steps.fork.outputs.fork_url }}
        DEFAULT_BRANCH: ${{ inputs.default_branch }}
        MAX_ACU_PER_SESSION: ${{ inputs.max_acu_per_session }}
        DRY_RUN: ${{ inputs.dry_run }}
        RUN_NUMBER: ${{ github.run_number }}
        RUN_ID: ${{ github.run_id }}
      run: |
        python "${{ github.action_path }}/scripts/dispatch_devin.py"\
          "${{ runner.temp }}/codeql-output/batches.json" \
          "${{ runner.temp }}/codeql-output"

    - name: Persist run logs
      id: persist-logs
      if: inputs.persist_logs == 'true' && inputs.github_token != ''
      shell: bash
      timeout-minutes: 5
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        TARGET_REPO: ${{ env.SCAN_REPO_URL }}
        REPO_DIR: ${{ runner.temp }}/target-repo
        RUN_LABEL: ${{ steps.parse.outputs.run_label }}
      run: |
        python "${{ github.action_path }}/scripts/persist_logs.py" \
          "${{ runner.temp }}/codeql-output"

    - name: Push telemetry to action repo
      if: inputs.github_token != ''
      shell: bash
      timeout-minutes: 5
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        ACTION_REPO: ${{ github.repository }}
        TARGET_REPO: ${{ env.SCAN_REPO_URL }}
        FORK_URL: ${{ steps.fork.outputs.fork_url }}
        RUN_NUMBER: ${{ github.run_number }}
        RUN_ID: ${{ github.run_id }}
        RUN_LABEL: ${{ steps.parse.outputs.run_label }}
      run: |
        python "${{ github.action_path }}/scripts/persist_telemetry.py" \
          "${{ runner.temp }}/codeql-output"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: codeql-devin-results
        path: |
          ${{ runner.temp }}/codeql-output/
          ${{ runner.temp }}/codeql-results/
        retention-days: 30
