name: "CodeQL Devin Fixer"
description: "Run CodeQL analysis, prioritize security issues, and dispatch Devin sessions to fix them in batches"

inputs:
  target_repo:
    description: "GitHub repository URL to analyze (e.g., https://github.com/owner/repo)"
    required: true
  languages:
    description: "Comma-separated CodeQL languages (e.g., javascript,python). Auto-detected if empty."
    required: false
    default: ""
  queries:
    description: "CodeQL query suite to run (e.g., security-extended, security-and-quality)"
    required: false
    default: "security-extended"
  include_paths:
    description: "Optional newline- or comma-separated globs to include (limits analysis scope)"
    required: false
    default: ""
  exclude_paths:
    description: "Optional newline- or comma-separated globs to exclude from analysis"
    required: false
    default: ""
  batch_size:
    description: "Maximum number of issues per Devin session/batch"
    required: false
    default: "5"
  max_sessions:
    description: "Maximum number of Devin sessions to create"
    required: false
    default: "10"
  severity_threshold:
    description: "Minimum severity to include: critical, high, medium, low"
    required: false
    default: "low"
  devin_api_key:
    description: "Devin API key for creating fix sessions"
    required: true
  max_acu_per_session:
    description: "Maximum ACU limit per Devin session (leave empty for default)"
    required: false
    default: ""
  dry_run:
    description: "If true, generate prompts but don't create Devin sessions"
    required: false
    default: "false"
  default_branch:
    description: "Default branch of the target repo"
    required: false
    default: "main" 

outputs:
  total_issues:
    description: "Total number of security issues found"
    value: ${{ steps.parse.outputs.total_issues }}
  total_batches:
    description: "Number of batches created"
    value: ${{ steps.parse.outputs.total_batches }}
  sessions_created:
    description: "Number of Devin sessions created"
    value: ${{ steps.dispatch.outputs.sessions_created }}
  session_urls:
    description: "Comma-separated list of Devin session URLs"
    value: ${{ steps.dispatch.outputs.session_urls }}

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Python dependencies
      shell: bash
      run: pip install requests

    - name: Clone target repository
      shell: bash
      env:
        GIT_LFS_SKIP_SMUDGE: "1"
      run: |
        TARGET_DIR="${{ runner.temp }}/target-repo"
        git clone --depth 1 --single-branch "${{ inputs.target_repo }}" "$TARGET_DIR"
        echo "TARGET_DIR=$TARGET_DIR" >> "$GITHUB_ENV" 

    - name: Detect languages
      id: detect-lang
      shell: bash
      run: |
        if [ -n "${{ inputs.languages }}" ]; then
          echo "languages=${{ inputs.languages }}" >> "$GITHUB_OUTPUT"
          echo "Using specified languages: ${{ inputs.languages }}"
          exit 0
        fi

        TARGET_DIR="${{ runner.temp }}/target-repo"
        LANGS=""

        has_files() {
          local result
          result=$(find "$TARGET_DIR" \( "$@" \) -print -quit 2>/dev/null)
          [ -n "$result" ]
        }

        if has_files -name "*.js" -o -name "*.ts" -o -name "*.jsx" -o -name "*.tsx"; then
          LANGS="${LANGS:+$LANGS,}javascript"
        fi
        if has_files -name "*.py"; then
          LANGS="${LANGS:+$LANGS,}python"
        fi
        if has_files -name "*.java"; then
          LANGS="${LANGS:+$LANGS,}java"
        fi
        if has_files -name "*.go"; then
          LANGS="${LANGS:+$LANGS,}go"
        fi
        if has_files -name "*.rb"; then
          LANGS="${LANGS:+$LANGS,}ruby"
        fi
        if has_files -name "*.cs"; then
          LANGS="${LANGS:+$LANGS,}csharp"
        fi
        if has_files -name "*.cpp" -o -name "*.c" -o -name "*.h"; then
          LANGS="${LANGS:+$LANGS,}cpp"
        fi
        if has_files -name "*.swift"; then
          LANGS="${LANGS:+$LANGS,}swift"
        fi

        if [ -z "$LANGS" ]; then
          echo "No supported languages detected, defaulting to javascript"
          LANGS="javascript"
        fi

        echo "languages=$LANGS" >> "$GITHUB_OUTPUT"
        echo "Detected languages: $LANGS"

    - name: Prepare CodeQL config
      id: prepare-config
      shell: bash
      run: |
        CONFIG="${{ runner.temp }}/codeql-config.yml"
        INC="${{ inputs.include_paths }}"
        EXC="${{ inputs.exclude_paths }}"
        sanitize() {
          echo "$1" | tr ',' '\n' | sed '/^\s*$/d' | sed 's/^\s*//;s/\s*$//'
        }
        has_config=false
        echo "version: 2" > "$CONFIG"
        echo "queries: ${{ inputs.queries }}" >> "$CONFIG"
        INCL=$(sanitize "$INC")
        EXCL=$(sanitize "$EXC")
        if [ -n "$INCL" ] || [ -n "$EXCL" ]; then
          has_config=true
          echo "paths:" >> "$CONFIG"
          if [ -n "$INCL" ]; then
            sanitize "$INC" | sed 's/^/- /' >> "$CONFIG"
          fi
          if [ -n "$EXCL" ]; then
            echo "paths-ignore:" >> "$CONFIG"
            sanitize "$EXC" | sed 's/^/- /' >> "$CONFIG"
          fi
        fi
        echo "config_path=$CONFIG" >> "$GITHUB_OUTPUT"
        echo "has_config=$has_config" >> "$GITHUB_OUTPUT"

    - name: Initialize CodeQL (with config)
      if: steps.prepare-config.outputs.has_config == 'true'
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ steps.detect-lang.outputs.languages }}
        source-root: ${{ runner.temp }}/target-repo
        config-file: ${{ steps.prepare-config.outputs.config_path }}

    - name: Initialize CodeQL
      if: steps.prepare-config.outputs.has_config != 'true'
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ steps.detect-lang.outputs.languages }}
        source-root: ${{ runner.temp }}/target-repo
        queries: ${{ inputs.queries }}

    - name: Build CodeQL database (autobuild)
      uses: github/codeql-action/autobuild@v3
      env:
        LGTM_SRC: ${{ runner.temp }}/target-repo

    - name: Run CodeQL analysis
      uses: github/codeql-action/analyze@v3
      id: codeql-analyze
      with:
        output: ${{ runner.temp }}/codeql-results
        upload: never
        upload-database: true
        wait-for-processing: true

    - name: Find SARIF file
      id: find-sarif
      shell: bash
      run: |
        SARIF_DIR="${{ runner.temp }}/codeql-results"
        SARIF_FILE=$(find "$SARIF_DIR" -name "*.sarif" -type f | head -1)
        if [ -z "$SARIF_FILE" ]; then
          echo "ERROR: No SARIF file found in $SARIF_DIR"
          ls -la "$SARIF_DIR" || true
          exit 1
        fi
        echo "sarif_file=$SARIF_FILE" >> "$GITHUB_OUTPUT"
        echo "Found SARIF: $SARIF_FILE"

    - name: Parse SARIF and create batches
      id: parse
      shell: bash
      env:
        BATCH_SIZE: ${{ inputs.batch_size }}
        MAX_SESSIONS: ${{ inputs.max_sessions }}
        SEVERITY_THRESHOLD: ${{ inputs.severity_threshold }}
      run: |
        python "${{ github.action_path }}/scripts/parse_sarif.py" \
          "${{ runner.temp }}/codeql-results" \
          "${{ runner.temp }}/codeql-output"

    - name: Dispatch Devin sessions
      id: dispatch
      shell: bash
      env:
        DEVIN_API_KEY: ${{ inputs.devin_api_key }}
        TARGET_REPO: ${{ inputs.target_repo }}
        DEFAULT_BRANCH: ${{ inputs.default_branch }}
        MAX_ACU_PER_SESSION: ${{ inputs.max_acu_per_session }}
        DRY_RUN: ${{ inputs.dry_run }}
      run: |
        python "${{ github.action_path }}/scripts/dispatch_devin.py" \
          "${{ runner.temp }}/codeql-output/batches.json" \
          "${{ runner.temp }}/codeql-output"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: codeql-devin-results
        path: |
          ${{ runner.temp }}/codeql-output/
          ${{ runner.temp }}/codeql-results/
        retention-days: 30
